# Generated by Django 5.2.1 on 2025-05-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_category',
            new_name='variation_category',
        ),
    ]
